export class TestConfigurationVM{
  "allowCalculator": boolean = true;
  "allowSectionSelection": boolean = true;
  "aptitude": number = 0;
  "comprehension": number = 0;
  "cutoff": boolean = true;
  "doNotShowReport": boolean = true;
  "freeTest": boolean = true;
  "hideAllCharts": boolean = true;
  "hideAnalysis": boolean = true;
  "hideAreaWiseAnalysis": boolean = true;
  "hideDifficultyLevelAnalysis": boolean = true;
  "hideRank": boolean = true;
  "hideScoreCard": boolean = true;
  "hideSolutionAndQuestionSummary": boolean = true;
  "hideTopicWiseAnalysis": boolean = true;
  "maxAttempts": number = 0;
  "overall": number = 0;
  "percentile": boolean = true;
  "questionWiseAnalysis": boolean = true;
  "reasoning": number = 0;
  "reviewTestReport": boolean = true;
  "sectionWiseAnalysis": boolean = true;
  "sectionalBreakup": boolean = true;
  "shuffleQuestions": boolean = true;
  "viewSolution": boolean = true;
  "viewTestResult": boolean = true;
  "testId" : string = "";
}